config/routes.rb
Alert::Application.routes.draw do
  resources :balerts

end

app/models/balert.rb
class Balert < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/balerts_controller.rb
class BalertsController < ApplicationController
  # GET /balerts
  # GET /balerts.json
  def index
    @balerts = Balert.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @balerts }
    end
  end

  # GET /balerts/1
  # GET /balerts/1.json
  def show
    @balert = Balert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @balert }
    end
  end

  # GET /balerts/new
  # GET /balerts/new.json
  def new
    @balert = Balert.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @balert }
    end
  end

  # GET /balerts/1/edit
  def edit
    @balert = Balert.find(params[:id])
  end

  # POST /balerts
  # POST /balerts.json
  def create
    @balert = Balert.new(params[:balert])

    respond_to do |format|
      if @balert.save
        format.html { redirect_to @balert, notice: 'Balert was successfully created.' }
        format.json { render json: @balert, status: :created, location: @balert }
      else
        format.html { render action: "new" }
        format.json { render json: @balert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /balerts/1
  # PUT /balerts/1.json
  def update
    @balert = Balert.find(params[:id])

    respond_to do |format|
      if @balert.update_attributes(params[:balert])
        format.html { redirect_to @balert, notice: 'Balert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @balert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /balerts/1
  # DELETE /balerts/1.json
  def destroy
    @balert = Balert.find(params[:id])
    @balert.destroy

    respond_to do |format|
      format.html { redirect_to balerts_url }
      format.json { head :no_content }
    end
  end

  def gen_alert
    #Birthday
    @bdays = Balert.find(:all, :conditions => ["DAY(friend_dob) = ? AND MONTH(friend_dob) = ?", 2.days.from_now.day, 2.days.from_now.month])
    if !@bdays.empty?
       @bdays.each do |alertt| UserMailer.demo_mail(alertt,'Birthday').deliver! end
    end
    # Anniversary
    @anni = Balert.find(:all, :conditions => ["DAY(friend_marriage_anni_date) = ? AND MONTH(friend_marriage_anni_date) = ?", 2.days.from_now.day, 2.days.from_now.month])
    if !@anni.empty?
      @anni.each do |alertt| UserMailer.demo_mail(alertt,'Wedding Anniversary').deliver! end
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balerts_helper.rb
module BalertsHelper
end

app/views/balerts/_form.html.erb
<%= form_for(@balert) do |f| %>
  <% if @balert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@balert.errors.count, "error") %> prohibited this balert from being saved:</h2>

      <ul>
      <% @balert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :user_email %><br />
    <%= f.text_field :user_email %>
  </div>
  <div class="field">
    <%= f.label :friend_name %><br />
    <%= f.text_field :friend_name %>
  </div>
  <div class="field">
    <%= f.label :friend_email %><br />
    <%= f.text_field :friend_email %>
  </div>
  <div class="field">
    <%= f.label :friend_dob %><br />
    <%= f.date_select :friend_dob, :start_year => 1950 %>
  </div>
  <div class="field">
    <%= f.label :friend_marriage_anni_date %><br />
    <%= f.date_select :friend_marriage_anni_date, :start_year => 1950 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/balerts/edit.html.erb
<h1>Editing balert</h1>

<%= render 'form' %>

<%= link_to 'Show', @balert %> |
<%= link_to 'Back', balerts_path %>

app/views/balerts/index.html.erb
<h1>Listing balerts</h1>

<table>
  <tr>
    <th>User name</th>
    <th>User email</th>
    <th>Friend name</th>
    <th>Friend email</th>
    <th>Friend dob</th>
    <th>Friend marriage anni date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @balerts.each do |balert| %>
  <tr>
    <td><%= balert.user_name %></td>
    <td><%= balert.user_email %></td>
    <td><%= balert.friend_name %></td>
    <td><%= balert.friend_email %></td>
    <td><%= balert.friend_dob %></td>
    <td><%= balert.friend_marriage_anni_date %></td>
    <td><%= link_to 'Show', balert %></td>
    <td><%= link_to 'Edit', edit_balert_path(balert) %></td>
    <td><%= link_to 'Destroy', balert, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Balert', new_balert_path %>

app/views/balerts/new.html.erb
<h1>New balert</h1>

<%= render 'form' %>

<%= link_to 'Back', balerts_path %>

app/views/balerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User name:</b>
  <%= @balert.user_name %>
</p>

<p>
  <b>User email:</b>
  <%= @balert.user_email %>
</p>

<p>
  <b>Friend name:</b>
  <%= @balert.friend_name %>
</p>

<p>
  <b>Friend email:</b>
  <%= @balert.friend_email %>
</p>

<p>
  <b>Friend dob:</b>
  <%= @balert.friend_dob %>
</p>

<p>
  <b>Friend marriage anni date:</b>
  <%= @balert.friend_marriage_anni_date %>
</p>


<%= link_to 'Edit', edit_balert_path(@balert) %> |
<%= link_to 'Back', balerts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alert</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>